online_store/authuser/urls.py
from django.urls import path
from authuser import views

app_name = 'authuser'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterView.as_view(), name='register')
]

online_store/catalog/urls.py
from django.urls import path
from catalog import views

app_name = 'catalog'

urlpatterns = [
    path('', views.ProductListView.as_view(), name='product_list'),
    path('product_detail/<int:pk>', views.ProductDetailView.as_view(), name='product_detail')
]

online_store/online_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from online_store import settings

urlpatterns = [
    path('', include('catalog.urls')),
    path('', include('shopping_cart.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('authuser.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

online_store/shopping_cart/urls.py
from django.urls import path
from shopping_cart import views

app_name = 'shopping_cart'

urlpatterns = [
    path('cart/', views.show_cart_view, name='show_cart'),
    path('cart/add/<int:product_id>/', views.add_to_cart_view, name='add_to_cart'),
    path('cart/clear', views.clear_cart_view, name='clear_cart'),
    path('cart/remove/<int:product_id>/', views.extract_from_cart_view, name='remove_from_cart'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('thank_you/', views.thank_you_view, name='thank_you')
]

online_store/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Store. {% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary bg-dark" data-bs-theme="dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'catalog:product_list' %}">Django Store</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'catalog:product_list' %}">Catalog</a>
            </li>
            {% if not user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'authuser:register' %}">Registration</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'authuser:login' %}">Login</a>
                </li>
            {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'authuser:logout' %}">Logout</a>
                </li>
            {% endif %}
          </ul>
        </div>
        <span class="navbar-text">
          {% if user.is_authenticated %}
            <a href="{% url 'shopping_cart:show_cart' %}" class="text-decoration-none">
            <i class="bi bi-basket2">&nbsp;</i>
                {{ user.email }}
            </a>
          {% endif %}
        </span>
      </div>
    </nav>
    <div class="container">
        {% if messages %}
            {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                  {{ message }}
                  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}
        {% block content %}{% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>