online_store/catalog/urls.py
from django.urls import path
from catalog import views

app_name = 'catalog'

urlpatterns = [
    path('', views.ProductListView.as_view(), name='product_list'),
    path('product_detail/<int:pk>', views.ProductDetailView.as_view(), name='product_detail')
]

online_store/online_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from online_store import settings

urlpatterns = [
    path('', include('catalog.urls')),
    path('', include('shopping_cart.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('authuser.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

online_store/shopping_cart/urls.py
from django.urls import path
from shopping_cart import views

app_name = 'shopping_cart'

urlpatterns = [
    path('cart/', views.show_cart_view, name='show_cart'),
    path('cart/add/<int:product_id>/', views.add_to_cart_view, name='add_to_cart'),
    path('cart/clear', views.clear_cart_view, name='clear_cart'),
    path('cart/remove/<int:product_id>/', views.extract_from_cart_view, name='remove_from_cart'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('thank_you/', views.thank_you_view, name='thank_you')
]

online_store/shopping_cart/models.py
from django.db import models
from catalog.models import Product
from authuser.models import User


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Cart ({self.user})'

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f'({self.cart.user}) {self.product.name} * {self.quantity}'

    def get_cost(self):
        return self.product.price * self.quantity


class Order(models.Model):

    STATUS_CHOICES = [
        ("PENDING", "Pending"),
        ("PROCESSING", "Processing"),
        ("SHIPPED", "Shipped"),
        ("DELIVERED", "Delivered"),
        ("CANCELED", "Canceled"),
        ("ONHOLD", "On hold")
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    placed_at = models.DateTimeField(auto_now_add=True)
    address = models.TextField()
    phone = models.CharField(max_length=12)
    status = models.CharField(max_length=100, choices=STATUS_CHOICES)

    def __str__(self):
        return f'Order #{self.pk} ({self.user})'

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()

    def __str__(self):
        return f'Order #{self.order.pk} ({self.order.user}). {self.product.name} * {self.quantity}'

    def get_cost(self):
        return self.product.price * self.quantity

online_store/shopping_cart/forms.py
from django.forms import ModelForm, TextInput, Textarea
from shopping_cart.models import Order


class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['phone', 'address']
        widgets = {
            'phone': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter your phone number'
            }),
            'address': Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Enter address'
            })
        }

online_store/shopping_cart/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views import View
from django.contrib import messages
from shopping_cart.forms import OrderForm
from shopping_cart.repository import ShoppingCartRepository
from shopping_cart.services import if_enough_stocks, NotEnoughStockException


@login_required()
def show_cart_view(request):
    repository = ShoppingCartRepository(request.user)
    cart = repository.get_cart()
    return render(request, 'shopping_cart/cart.html', {'cart': cart})


@login_required()
def add_to_cart_view(request, product_id):
    repository = ShoppingCartRepository(request.user)
    repository.add_to_cart(product_id)
    cart_items = repository.get_all_cart_items()
    try:
        if_enough_stocks(cart_items)
    except NotEnoughStockException as e:
        messages.error(request, str(e), extra_tags='alert-danger')
    # redirect to the same page from where you added item to the shopping cart
    return redirect(request.META.get('HTTP_REFERER', '/'))


@login_required()
def extract_from_cart_view(request, product_id):
    repository = ShoppingCartRepository(request.user)
    repository.extract_from_cart(product_id)
    return redirect('shopping_cart:show_cart')


@login_required()
def clear_cart_view(request):
    repository = ShoppingCartRepository(request.user)
    repository.clear_cart()
    return redirect('shopping_cart:show_cart')


@method_decorator(login_required, name='dispatch')
class CheckoutView(View):
    def get(self, request):
        repository = ShoppingCartRepository(request.user)
        cart_items = repository.get_all_cart_items()
        try:
            if_enough_stocks(cart_items)
        except NotEnoughStockException as e:
            messages.error(request, str(e), extra_tags='alert-danger')
        cart = repository.get_cart()
        form = OrderForm()
        return render(request, 'shopping_cart/checkout.html', {'cart': cart, 'form': form})

    def post(self, request):
        repository = ShoppingCartRepository(request.user)
        form = OrderForm(request.POST)
        # placing the order
        if form.is_valid():
            repository.create_order(form)
            return redirect('shopping_cart:thank_you')
        else:
            messages.error(request, 'Something went wrong. Please try again', extra_tags='alert-danger')
            return redirect('shopping_cart:checkout')


def thank_you_view(request):
    return render(request, 'shopping_cart/thank_you.html')

online_store/shopping_cart/templates/shopping_cart/cart.html
{% extends 'base.html' %}
{% block title %}
Shopping cart
{% endblock %}
{% block content%}
<h1>Shopping Cart</h1>
{% if cart.items.all %}
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Product</th>
            <th scope="col">Price</th>
            <th scope="col">Quantity</th>
            <th scope="col">Cost</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart.items.all %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td><a href="{% url 'catalog:product_detail' item.product.pk %}" class="text-decoration-none">{{ item.product.name }}</a></td>
                <td>${{ item.product.price|floatformat:2 }}</td>
                <td>
                    <a href="{% url 'shopping_cart:remove_from_cart' item.product.pk %}" role="button" class="btn btn-outline-secondary btn-sm">-1</a>
                    &nbsp;&nbsp;{{ item.quantity }}&nbsp;&nbsp;
                    <a href="{% url 'shopping_cart:add_to_cart' item.product.pk %}" role="button" class="btn btn-outline-secondary btn-sm">+1</a>
                </td>
                <td>${% widthratio item.product.price 1 item.quantity as result %}{{result|floatformat:2}}</td>
            </tr>
        {% endfor %}
            <tr>
                <th scope="row"></th>
                <td></td>
                <td></td>
                <td>Total:</td>
                <td>${{ cart.get_total_cost|floatformat:2 }}</td>
            </tr>
      </tbody>
    </table>
    <a href="{% url 'shopping_cart:clear_cart' %}" role="button" class="btn btn-light">Clear shopping cart</a>
{% else %}
    <p>Your shopping cart is empty</p>
{% endif %}
{% endblock %}

online_store/shopping_cart/templates/shopping_cart/checkout.html
{% extends 'base.html' %}
{% block title %}
Checkout
{% endblock %}
{% block content%}
<h1>Checkout</h1>
{% if cart.items.all %}
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Product</th>
            <th scope="col">Price</th>
            <th scope="col">Quantity</th>
            <th scope="col">Cost</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart.items.all %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td><a href="{% url 'catalog:product_detail' item.product.pk %}" class="text-decoration-none">{{ item.product.name }}</a></td>
                <td>${{ item.product.price|floatformat:2 }}</td>
                <td>
                    &nbsp;&nbsp;{{ item.quantity }}&nbsp;&nbsp;
                </td>
                <td>${% widthratio item.product.price 1 item.quantity as result %}{{result|floatformat:2}}</td>
            </tr>
        {% endfor %}
            <tr>
                <th scope="row"></th>
                <td></td>
                <td></td>
                <td>Total:</td>
                <td>${{ cart.get_total_cost|floatformat:2 }}</td>
            </tr>
      </tbody>
    </table>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit">
    </form>
{% else %}
    <p>Your shopping cart is empty</p>
{% endif %}
{% endblock %}

online_store/shopping_cart/templates/shopping_cart/thank_you.html
{% extends 'base.html' %}
{% block title %}
Order was placed
{% endblock %}
{% block content%}
<h1>Thank you for your order</h1>
<h2>Our managers will call you back soon</h2>
{% endblock %}